# Generated by Django 4.2.20 on 2025-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('short', 'Короткие нарды'), ('long', 'Длинные нарды')], default='short', max_length=5),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='side',
            field=models.CharField(choices=[('random', 'Случайно'), ('white', 'Белые'), ('black', 'Чёрные')], default='random', max_length=6),
        ),
    ]
